### ISSUE TITLE
Unable to read repository.

### ISSUE THREAD

**Issue by dmhines** [kwin/cppcheclipse#102]
Adding the update site "https://dl.bintray.com/cppcheclipse/p2/updates/" results in an error:
Unable to read repository at https://dl.bintray.com/cppcheclipse/p2/updates/content.xml.

**Comment by dmhines** [comment]
![unable to read repository](https://user-images.githubusercontent.com/14875811/71911000-8d7e0f80-3138-11ea-8d85-2b7134b770c2.PNG)

**Comment by Hansvdsteen** [comment]
@dmhines no problem here.... 

![image](https://user-images.githubusercontent.com/41508065/72283855-f20d0300-363f-11ea-974a-112577e67866.png)

**Comment by dmhines** [comment]
I was able to get it to download by using http instead of https.
