### ISSUE TITLE
Provide p2 update site

### ISSUE THREAD

**Issue by kwin** [kwin/cppcheclipse#72]
Different options are listed at https://groups.google.com/forum/#!topic/workspacemechanic/0Tw2mjBCgb0. Probably bintray is the best. There is even a script for uploading binaries at https://github.com/vogellacompany/bintray-publish-p2-updatesite/.

**Comment by jmccabe** [comment]
FWIW - having just read the section about bintray, it sounds like a good option to me.

**Comment by kwin** [comment]
The approach from https://github.com/LorenzoBettini/p2composite-bintray-example is the most promising one, as everything can be done with Maven/Tycho.

**Comment by kwin** [comment]
The new update site at https://dl.bintray.com/cppcheclipse/p2/updates/ is now available and automatically used for each new release.

**Comment by SergeySlice** [comment]
> The new update site at https://dl.bintray.com/cppcheclipse/p2/updates/ is now available and automatically used for each new release.

The link is not working.

**Comment by AntonKrug** [comment]
Hi @SergeySlice there is temporary workaround this described in the #108
