### ISSUE TITLE
Update site not found

### ISSUE THREAD

**Issue by jmccabe** [kwin/cppcheclipse#74]
I'm getting the following issue with the update site when trying to install cppcheclipse on Luna.

"No repository found at http://cppcheclipse.eclipselabs.org.codespot.com/svn/update/."

I don't know of anywhere else that I can report this but, if it all looks ok, please respond.

**Comment by kwin** [comment]
Unfortunately Google seems to have closed down that page. I will set up a new site which is tracked in #72 .

**Comment by jmccabe** [comment]
Thank you for your reply. I hadn't realised the loss of the existing site and the "Provide p2 update site" issue were related.
