### ISSUE TITLE
Update site broken

### ISSUE THREAD

**Issue by kyelok** [kwin/cppcheclipse#76]
http://cppcheclipse.eclipselabs.org.codespot.com/svn/update/
seems to be down at the moment.

**Comment by gajanak** [comment]
404 on URL 
http://cppcheclipse.eclipselabs.org.codespot.com/svn/update/

Is there an alternative installation way, without eclipse marketplace ?

**Comment by kyelok** [comment]
I got it to work by downloading v0.9.9 from the old website and doing a manual install:
old site:
https://code.google.com/archive/a/eclipselabs.org/p/cppcheclipse/downloads

manual install:
http://stackoverflow.com/questions/5482554/how-to-install-plugin-for-eclipse-from-zip
http://stackoverflow.com/questions/23199245/eclipse-manually-install-plugin

**Comment by creckord** [comment]
We've been getting error reports for the Eclipse Marketplace entry (http://marketplace.eclipse.org/content/cppcheclipse) as well, because it uses the same update site. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=494374

It would be great if you could update the update site there as well.

**Comment by kwin** [comment]
The provision of the new p2 repository is tracked in #72.
Unfortunately with the shutdown of Google Code they were also already shutting down the SVN repo which was used to host the previous p2 repository.

**Comment by kwin** [comment]
You find now a new p2 update site at https://dl.bintray.com/cppcheclipse/p2/updates/.
