### ISSUE TITLE
Feature request to support macros in the path

### ISSUE THREAD

**Issue by AntonKrug** [kwin/cppcheclipse#81]
Hi,

I'm wondering if it would be viable to add support for macros in the path, such as:

${eclipse_home}\cppcheck\cppcheck.exe

So the path could be relative to the installed directory. I would simplify for us bundling the cppcheck with our Eclipse.

**Comment by AntonKrug** [comment]
I made required changes on my fork, now it supports ${eclipse_home} macro, allowing the installation to be portable and relative to the eclipse installation folder.

And noticed your "Go to check description" action was opening old URL so I fixed that as well. Would you be interested in merging these features to your repo?

**Comment by kwin** [comment]
Please open a PR for this.

**Comment by AntonKrug** [comment]
I had to change from FileFieldEditor to StringFieldEditor, so there is no browse button. The FileFieldEditor even when disabling absolute path checks will still try to find the file before resolution and not allow invalid inputs from his perspective. While with StringFieldEditor it will allow using macros in the path/name.

Would that be ok for you?

**Comment by kwin** [comment]
Please open the PR first, then we can discuss best based on code (and with the correct context) directly within the PR.

**Comment by AntonKrug** [comment]
Made the PR https://github.com/kwin/cppcheclipse/pull/82
